sudo: required
services:
  - docker

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker pull profilid/profilid_proxy_server

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: profilid
  env: Profilid-env
  bucket_name: elasticbeanstalk-us-east-2-880701106342
  bucket_path: profilid_app
  on:
    branch: master
  access_key_id: '$AWS_ACCESS_KEY'
  secret_access_key: 'AWS_SECRET_KEY'
