services:
  - docker

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker pull profilid/profilid_proxy_server
  - docker pull profilid/profilid_client
  - docker pull profilid/profilid_auth
  - docker pull profilid/profilid_users
  - docker pull profilid/profilid_profiles
  - docker pull profilid/profilid_users_db
  - docker pull profilid/profilid_profiles_db
  - docker pull profilid/profilif_logstash

deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: profilid
  env: Profilid-env-1
  bucket_name: elasticbeanstalk-ap-south-1-880701106342
  bucket_path: profilid_app
  on:
    branch: master
  access_key_id: '$AWS_ACCESS_KEY'
  secret_access_key: '$AWS_SECRET_KEY'
